// @vitest-environment jsdom
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter } from "react-router";
import { Master } from "./master";
import { MASTER_STORAGE_KEY } from "../master/use-master";
import { masterSchema } from "../master/engine";
import { cardImageSource } from "./card-art";

beforeEach(() => {
  localStorage.clear();
  Object.defineProperty(HTMLElement.prototype, "setPointerCapture", { configurable: true, value: vi.fn() });
});
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals(); delete (HTMLElement.prototype as unknown as Record<string, unknown>).setPointerCapture; });
const saved = () => masterSchema.parse(JSON.parse(localStorage.getItem(MASTER_STORAGE_KEY)!));
it("guarda y retira cartas con iconos y permite limpiar el tablero en bloque", async () => {
  vi.spyOn(window, "confirm").mockReturnValue(true);
  const user = userEvent.setup();
  render(<MemoryRouter><Master characters={[]} /></MemoryRouter>);
  await user.type(await screen.findByLabelText("Nombre de campaña"), "Limpieza");
  await user.click(screen.getByRole("button", { name: "Crear campaña" }));
  await user.click(screen.getByRole("button", { name: "Barajas y herramientas" }));
  const draw = await screen.findByRole("button", { name: "Sacar carta al azar" });
  await user.click(draw); await user.click(draw);
  await user.click(within(screen.getAllByRole("article")[0]).getByRole("button", { name: /^Guardar .* en inventario$/ }));
  expect(saved().campaigns[0].table.storedCards).toHaveLength(1);
  await user.click(within(screen.getByRole("article")).getByRole("button", { name: /^Retirar .* del tablero$/ }));
  expect(saved().campaigns[0].table.cards).toHaveLength(0);
  await user.click(draw); await user.click(draw);
  await user.click(screen.getByRole("button", { name: "Acciones del tablero" }));
  await user.click(screen.getByRole("button", { name: "Guardar todas las cartas en inventario" }));
  expect(saved().campaigns[0].table.storedCards).toHaveLength(3);
  expect(saved().campaigns[0].table.cards).toHaveLength(0);
  await user.click(draw);
  await user.click(screen.getByRole("button", { name: "Acciones del tablero" }));
  await user.click(screen.getByRole("button", { name: "Retirar cartas de la mesa" }));
  expect(saved().campaigns[0].table.cards).toHaveLength(0);
  await user.click(screen.getByRole("button", { name: "Colocar ficha roja" }));
  await user.click(screen.getByRole("button", { name: "Acciones del tablero" }));
  await user.click(screen.getByRole("button", { name: "Reiniciar tablero" }));
  expect(saved().campaigns[0].table.tokens).toHaveLength(0);
  expect(saved().campaigns[0].table.storedCards).toHaveLength(3);
});
it("carga un mapa desde el PC y conserva su tamaño al ampliarlo", async () => {
  class DecodedImage {
    naturalWidth = 600;
    naturalHeight = 300;
    onload: (() => void) | null = null;
    set src(_value: string) { queueMicrotask(() => this.onload?.()); }
  }
  vi.stubGlobal("Image", DecodedImage);
  const user = userEvent.setup();
  render(<MemoryRouter><Master characters={[]} /></MemoryRouter>);
  await user.type(await screen.findByLabelText("Nombre de campaña"), "Mapa local");
  await user.click(screen.getByRole("button", { name: "Crear campaña" }));
  await user.click(screen.getByRole("button", { name: "Barajas y herramientas" }));
  await user.click(screen.getByText("Escenario"));
  await user.upload(screen.getByLabelText("Cargar mapa como imagen"), new File([new Uint8Array([137, 80, 78, 71])], "mapa.png", { type: "image/png" }));
  await screen.findByRole("img", { name: "mapa.png" });
  expect(saved().campaigns[0].table.imageMaps[0].image).toMatch(/^data:image\/png;base64,/);
  await user.click(screen.getByRole("button", { name: "Ajustar mapa mapa.png" }));
  await user.click(screen.getByRole("button", { name: "Ampliar mapa" }));
  expect(saved().campaigns[0].table.imageMaps[0]).toMatchObject({ width: 750, height: 375 });
  await user.click(screen.getByRole("button", { name: "Retirar de la mesa" }));
  expect(saved().campaigns[0].table.imageMaps).toHaveLength(0);
});
it("eleva la carta pulsada por encima de las demás sin abrir detalles", async () => {
  const user = userEvent.setup();
  render(<MemoryRouter><Master characters={[]} /></MemoryRouter>);
  await user.type(await screen.findByLabelText("Nombre de campaña"), "Cartas");
  await user.click(screen.getByRole("button", { name: "Crear campaña" }));
  await user.click(screen.getByRole("button", { name: "Barajas y herramientas" }));
  await user.click(screen.getByRole("button", { name: "Buscar" }));
  await user.click(await screen.findByRole("button", { name: "Colocar · Ruinas bajo la niebla" }));
  await user.click(screen.getByRole("button", { name: "Colocar · El bosque de los ecos" }));
  const first = screen.getByRole("article", { name: "Mover Ruinas bajo la niebla" });
  await user.click(first);
  expect(saved().campaigns[0].table.cards.at(-1)?.definition.name).toBe("Ruinas bajo la niebla");
  expect(first.style.zIndex).toBe("3");
  expect(screen.queryByLabelText("Notas de la carta")).toBeNull();
  expect(within(first).getByRole("img").getAttribute("src")).toBe(cardImageSource(saved().campaigns[0].table.cards.at(-1)!.definition.image!));
});
it("conserva mesa y notas, y abre detalles solo con el botón", async () => {
  const user = userEvent.setup();
  const view = render(<MemoryRouter initialEntries={["/?modo=master"]}><Master characters={[]} /></MemoryRouter>);
  await user.type(await screen.findByLabelText("Nombre de campaña"), "La cripta");
  await user.click(screen.getByRole("button", { name: "Crear campaña" }));
  await user.click(screen.getByRole("button", { name: "Barajas y herramientas" }));
  expect(screen.queryByText("Música ambiente")).toBeNull();
  await user.click(await screen.findByRole("button", { name: "Sacar carta al azar" }));
  await waitFor(() => expect(saved().campaigns[0].table.cards).toHaveLength(1));
  const card = saved().campaigns[0].table.cards[0];
  const handle = screen.getByRole("article", { name: `Mover ${card.definition.name}` });
  handle.focus(); await user.keyboard("{ArrowRight}");
  expect(saved().campaigns[0].table.cards[0].x).toBe(card.x + 20);
  vi.stubGlobal("PointerEvent", MouseEvent);
  Object.defineProperty(HTMLElement.prototype, "setPointerCapture", { configurable: true, value: vi.fn() });
  const body = within(handle).getByText(card.definition.description);
  fireEvent.pointerDown(body, { button: 0, clientX: 100, clientY: 100 });
  fireEvent.pointerMove(body, { clientX: 130, clientY: 140 });
  fireEvent.pointerUp(body, { clientX: 130, clientY: 140 });
  expect(saved().campaigns[0].table.cards[0]).toMatchObject({ x: card.x + 50, y: card.y + 40 });
  expect(screen.queryByRole("region", { name: "Pieza seleccionada" })).toBeNull();
  await user.click(handle);
  expect(screen.queryByLabelText("Notas de la carta")).toBeNull();
  await user.click(screen.getByRole("button", { name: `Ver detalles de ${card.definition.name}` }));
  expect(screen.getByLabelText("Notas de la carta")).toBeTruthy();
  expect(screen.getByRole("link", { name: /Abrir sugerencia musical/ }).getAttribute("href")).toBe(card.definition.musicUrl);
  await user.click(screen.getByRole("button", { name: "Guardar carta en inventario" }));
  expect(saved().campaigns[0].table.cards).toHaveLength(0);
  expect(saved().campaigns[0].table.storedCards).toHaveLength(1);
  await user.click(screen.getByRole("button", { name: "Inventario" }));
  await user.click(screen.getByRole("button", { name: `Colocar guardada · ${card.definition.name}` }));
  expect(saved().campaigns[0].table.cards).toHaveLength(1);
  expect(saved().campaigns[0].table.storedCards).toHaveLength(0);
  await user.click(screen.getByRole("button", { name: "Colocar ficha roja" }));
  expect(saved().campaigns[0].table.tokens[0].label).toBe("Ficha");
  await user.click(screen.getByRole("button", { name: "Colocar ficha verde" }));
  await user.click(screen.getAllByRole("button", { name: "Ver detalles de ficha · Ficha" })[1]);
  await user.clear(screen.getByLabelText("Nombre de ficha"));
  await user.type(screen.getByLabelText("Nombre de ficha"), "Puerta");
  await user.click(screen.getByRole("button", { name: "Guardar nombre de ficha" }));
  expect(saved().campaigns[0].table.tokens[1].label).toBe("Puerta");
  await user.click(screen.getByRole("button", { name: "Cerrar detalle" }));
  await user.click(screen.getByText("Escenario"));
  await user.click(screen.getByRole("button", { name: "Ver mapas del catálogo" }));
  await user.click(await screen.findByRole("button", { name: "Patio de las ruinas" }));
  expect(saved().campaigns[0].table.map?.id).toBe("map-ruinas");
  const viewport = screen.getByLabelText("Mesa desplazable");
  const left = viewport.scrollLeft; const top = viewport.scrollTop;
  fireEvent.pointerDown(viewport, { button: 0, clientX: 300, clientY: 300 });
  fireEvent.pointerMove(viewport, { clientX: 350, clientY: 330 });
  fireEvent.pointerUp(viewport, { clientX: 350, clientY: 330 });
  expect(viewport.scrollLeft).toBe(left - 50);
  expect(viewport.scrollTop).toBe(top - 30);
  await user.click(screen.getByRole("button", { name: "Ocultar sugerencias" }));
  expect(saved().campaigns[0].table.cards).toHaveLength(1);
  await user.click(screen.getByRole("button", { name: /Volver al cuaderno/ }));
  await user.click(screen.getByRole("button", { name: "Notas" }));
  await user.type(screen.getByLabelText("Notas del master"), "La llave está junto al puente.");
  await user.click(screen.getByRole("button", { name: "Guardar notas" }));
  expect(saved().campaigns[0].notes).toContain("La llave");
  expect(screen.queryByRole("button", { name: "Encuentros" })).toBeNull();
  const campaign = saved().campaigns[0];
  view.unmount();
  render(<MemoryRouter initialEntries={[`/?modo=master&campana=${campaign.id}&seccion=notas`]}><Master characters={[]} /></MemoryRouter>);
  await screen.findByLabelText("Notas del master");
  expect((screen.getByLabelText("Notas del master") as HTMLTextAreaElement).value).toContain("La llave");
  expect(saved().campaigns[0].table.cards).toHaveLength(1);
});
it("mantiene en memoria la sesión si falla el almacenamiento y protege datos corruptos", async () => {
  localStorage.setItem(MASTER_STORAGE_KEY, "corrupt");
  const user = userEvent.setup();
  render(<MemoryRouter initialEntries={["/?modo=master"]}><Master characters={[]} /></MemoryRouter>);
  await screen.findByRole("alert");
  await user.type(screen.getByLabelText("Nombre de campaña"), "Sesión temporal");
  await user.click(screen.getByRole("button", { name: "Crear campaña" }));
  expect(localStorage.getItem(MASTER_STORAGE_KEY)).toBe("corrupt");
  expect(screen.getByRole("heading", { name: "Sesión temporal" })).toBeTruthy();
  expect(screen.getByRole("button", { name: "Descargar cuaderno original" })).toBeTruthy();
  expect(screen.getByRole("button", { name: "Exportar sesión del master" })).toBeTruthy();
});
it("ofrece exportación cuando el navegador rechaza las escrituras", async () => {
  vi.spyOn(Storage.prototype, "setItem").mockImplementation(() => { throw new Error("quota"); });
  const user = userEvent.setup();
  render(<MemoryRouter><Master characters={[]} /></MemoryRouter>);
  await user.type(await screen.findByLabelText("Nombre de campaña"), "Memoria");
  await user.click(screen.getByRole("button", { name: "Crear campaña" }));
  expect(screen.getByRole("alert").textContent).toContain("sesión sigue en memoria");
  expect(screen.getByRole("heading", { name: "Memoria" })).toBeTruthy();
});


